basePath: /api/v1
definitions:
  model.ROLE:
    enum:
    - user
    - admin
    type: string
    x-enum-varnames:
    - USER
    - ADMIN
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/model.ROLE'
      username:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:18888
info:
  contact: {}
  description: This is a sample server Account API.
  title: Swagger Account API
  version: "1.0"
paths:
  /public/send_info:
    post:
      consumes:
      - application/json
      description: Send info register
      parameters:
      - description: Send info
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Send info register
      tags:
      - Register
swagger: "2.0"
